baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
# Change the default theme
theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]